[package]
name = "cdt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-ord = "0.3.2"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.3"
