name: Kani CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  run-kani:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@v3
      
      - uses: Swatinem/rust-cache@v2

      - name: Kani Rust Verifier
        uses: model-checking/kani-github-action@v0.36